# 03. Classifier Stress Test

Run the classifier across all downloaded bills.
Goal: find `unknown` nodes and false positives to drive pattern improvements in `classify_bill.py`.

In [1]:
import sys
from pathlib import Path

import pandas as pd

sys.path.insert(0, "..")

from bill_tree import normalize_bill
from financial_classifier.classify_bill import DOLLAR, PRIMARY_LABELS, build_financial_df, check_coverage, classify_text

## Load and classify all bills

One version per bill (first downloaded). Adjust `xmls[0]` to target a specific version.

In [2]:
BILLS_DIR = Path("../bills")

rows = []
for bill_dir in sorted(BILLS_DIR.iterdir()):
    if not bill_dir.is_dir():
        continue
    xmls = sorted(bill_dir.glob("*.xml"))
    if not xmls:
        continue
    try:
        tree = normalize_bill(xmls[0])  # first version only
    except Exception as e:
        print(f"SKIP {bill_dir.name}: {e}")
        continue
    for n in tree.nodes:
        if not DOLLAR.search(n.body_text or ""):
            continue
        rows.append(
            {
                "bill": bill_dir.name,
                "label": classify_text(n.body_text),
                "path": " > ".join(n.display_path[-2:]) if n.display_path else "",
                "preview": (n.body_text or "")[:120],
                "body_text": n.body_text or "",
            }
        )

df = pd.DataFrame(rows)
print(f"{len(df)} dollar-amount nodes across {df['bill'].nunique()} bills")
df["label"].value_counts()

273 dollar-amount nodes across 2 bills

label
unknown          132
appropriation    116
fee                7
restriction        5
cap                5
directive          4
transfer           4
Name: count, dtype: int64

In [3]:
for _, row in df[df["label"] == "cap"].iterrows():
    print(row["bill"], "|", row["path"])
    print()
    print(row["body_text"])
    print("---")

118-hr-4366 | Administrative provisions > sec. 119

Notwithstanding any other provision of law, funds made available in this title for operation and maintenance of family housing shall be the exclusive source of funds for repair and maintenance of all family housing units, including general or flag officer quarters: Provided, That not more than $15,000 per unit may be spent annually for the maintenance and repair of any general or flag officer quarters without 30 days prior notification, or 14 days for a notification provided in an electronic medium pursuant to sections 480 and 2883 of title 10, United States Code, to the Committees on Appropriations of both Houses of Congress, except that an after-the-fact notification shall be submitted if the limitation is exceeded solely due to costs associated with environmental remediation that could not be reasonably anticipated at the time of the budget submission: Provided further, That the Under Secretary of Defense (Comptroller) is to report annually to the Committees on Appropriations of both Houses of Congress all operation and maintenance expenditures for each individual general or flag officer quarters for the prior fiscal year.
---
118-hr-4366 | Administrative provisions > sec. 210

Funds available in this title or funds for salaries and other administrative expenses shall also be available to reimburse the Office of Resolution Management, Diversity and Inclusion, the Office of Employment Discrimination Complaint Adjudication, and the Alternative Dispute Resolution function within the Office of Human Resources and Administration for all services provided at rates which will recover actual costs but not to exceed $86,481,000 for the Office of Resolution Management, Diversity and Inclusion, $6,960,000 for the Office of Employment Discrimination Complaint Adjudication, and $7,772,000 for the Alternative Dispute Resolution function within the Office of Human Resources and Administration: Provided, That payments may be made in advance for services to be furnished based on estimated costs: Provided further, That amounts received shall be credited to the General Administration and Information Technology Systems accounts for use by the office that provided the service.
---
119-hr-1 | sec. 30021 > (d) Repayment Assistance Plan

(d)Repayment Assistance Plan Section 455 of the Higher Education Act of 1965 (20 U.S.C. 1087e) is amended by adding at the end the following new subsection:(q)Repayment Assistance Plan(1)In general Notwithstanding any other provision of this Act, beginning on July 1, 2026, the Secretary shall carry out an income-based repayment plan (to be known as the Repayment Assistance Plan), that shall have the following terms and conditions:(A)The total monthly repayment amount owed by a borrower for all of the loans of the borrower that are repaid pursuant to the Repayment Assistance Plan shall be equal to the applicable monthly payment of a borrower calculated under paragraph(3)(B), except that the borrower may not be precluded from repaying an amount that exceeds such amount for any month.(B)The Secretary shall apply the borrower’s applicable monthly payment under this paragraph first toward interest due on each such loan, next toward any fees due on each loan, and then toward the principal of each loan.(C)Any principal due and not paid under subparagraph(B) or paragraph(2)(B) shall be deferred.(D)A borrower who is not in a period of deferment or forbearance shall make an applicable monthly payment for each month until the earlier of—(i)the date on which the outstanding balance of principal and interest due on all of the loans of the borrower that are repaid pursuant to the Repayment Assistance Plan is $0; or(ii)the date on which the borrower has made 360 qualifying monthly payments.(E)The Secretary shall repay or cancel any outstanding balance of principal and interest due on a loan made under this part to a borrower—(i)who, for any period of time, participated in the Repayment Assistance Plan under this subsection;(ii)whose most recent payment for such loan prior to the loan cancellation under this subparagraph was made under such Repayment Assistance Plan; and(iii)who has made 360 qualifying monthly payments on such loan.(F)For the purposes of this subsection, the term qualifying monthly payment means any of the following:(i)An on-time applicable monthly payment under this subsection.(ii)An on-time monthly payment under the standard repayment plan under subsection(d)(7)(A)(i) of not less than the monthly payment required under such plan.(iii)A monthly payment under any repayment plan of not less than the monthly payment that would be required under a standard repayment plan under section 455(d)(1)(A) with a repayment period of 10 years.(iv)A monthly payment under section 493C of not less than the monthly payment required under such section, including a monthly payment equal to the minimum payment amount permitted under such section.(v)A monthly payment made before the date of enactment of this subsection under an income-contingent repayment plan carried out under section 455(d)(1)(D) (or under an alternative repayment plan in lieu of repayment under such an income-contingent repayment plan, if placed in such an alternative repayment plan by the Secretary) of not less than the monthly payment required under such a plan, including a monthly payment equal to the minimum payment amount permitted under such a plan.(vi)A month when the borrower did not make a payment because the borrower was in deferment due to an economic hardship described in section 435(o).(vii)A month that ended before the date of enactment of this subsection when the borrower did not make a payment because the borrower was in a period deferment or forbearance described in section 685.209(k)(4)(iv) of title 34, Code of Federal Regulations (as in effect on the date of enactment of this subsection).(G)With respect to carrying out section 494(a)(2) for the Repayment Assistance Plan, an individual may elect to opt out of the disclosures required under section 494(a)(2)(A)(ii) in accordance with the procedures established under section 493C(c)(2)(B).(2)Balance assistance for distressed borrowers(A)Interest subsidy With respect to a borrower of a loan made under this part, for each month for which such a borrower makes an on-time applicable monthly payment required under paragraph(1)(A) and such monthly payment is insufficient to pay the total amount of interest that accrues for the month on all loans of the borrower repaid pursuant to the Repayment Assistance Plan under this subsection, the amount of interest accrued and not paid for the month shall not be charged to the borrower.(B)Matching principal payment With respect to a borrower of a loan made under this part and not in a period of deferment or forbearance, for each month for which a borrower makes an on-time applicable monthly payment required under paragraph(1)(A) and such monthly payment reduces the total outstanding principal balance of all loans of the borrower repaid pursuant to the Repayment Assistance Plan under this subsection by less than $50, the Secretary shall reduce such total outstanding principal balance of the borrower by an amount that is equal to—(i)the amount that is the lesser of—(I)$50; or (II)the total amount paid by the borrower for such month pursuant to paragraph(1)(A), minus(ii)the total amount paid by the borrower for such month pursuant to paragraph(1)(A) that is applied to such total outstanding principal balance.(3)Definitions In this paragraph:(A)Adjusted gross income The term adjusted gross income, when used with respect to a borrower, means the adjusted gross income (as such term is defined in section 62 of the Internal Revenue Code of 1986) of the borrower (and the borrower’s spouse, as applicable) for the most recent taxable year, except that, in the case of a married borrower who files a separate Federal income tax return, the term does not include the adjusted gross income of the borrower’s spouse.(B)Applicable monthly payment(i)In general Except as provided in clause(ii) or(iii), the term applicable monthly payment means, when used with respect to a borrower, the amount equal to—(I)the applicable base payment of the borrower, divided by 12; minus (II)$50 for each dependent child of the borrower.(ii)Minimum amount In the case of a borrower with an applicable monthly payment amount calculated under clause(i) that is less than $10, the applicable monthly payment of the borrower shall be $10.(iii)Final payment In the case of a borrower whose total outstanding balance of principal and interest on all of the loans of the borrower that are repaid pursuant to the Repayment Assistance Plan is less than the applicable monthly payment calculated pursuant to clause(i) or(ii), as applicable, then the applicable monthly payment of the borrower shall be the total outstanding balance of principal and interest on all such loans.(iv)Base payment The amount of the applicable base payment for a borrower with an adjusted gross income of—(I)not more than $10,000, is $120; (II)more than $10,000 and not more than $20,000, is 1 percent of such adjusted gross income; (III)more than $20,000 and not more than $30,000, is 2 percent of such adjusted gross income; (IV)more than $30,000 and not more than $40,000, is 3 percent of such adjusted gross income;(V)more than $40,000 and not more than $50,000, is 4 percent of such adjusted gross income; (VI)more than $50,000 and not more than $60,000, is 5 percent of such adjusted gross income; (VII)more than $60,000 and not more than $70,000, is 6 percent of such adjusted gross income; (VIII)more than $70,000 and not more than $80,000, is 7 percent of such adjusted gross income; (IX)more than $80,000 and not more than $90,000, is 8 percent of such adjusted gross income;(X)more than $90,000 and not more than $100,000, is 9 percent of such adjusted gross income; and (XI)more than $100,000, is 10 percent of such adjusted gross income.(v)Dependent child of the borrower For the purposes of this paragraph, the term dependent child of the borrower means an individual who—(I)is under 17 years of age; and (II)is the borrower’s dependent child or another person who lives with and receives more than one-half of their support from the borrower..
---
119-hr-1 | Loan Repayment > sec. 30025

Paragraph(1) of section 458(a) of the Higher Education Act of 1965 (20 U.S.C. 1087h(a)(1)) is amended to read as follows:(1)Additional mandatory funds for fiscal years 2025 and 2026 For each of the fiscal years 2025 and 2026 there shall be available to the Secretary (in addition to any other amounts appropriated under any appropriations Act for administrative costs under this part and part B and out of any money in the Treasury not otherwise appropriated) funds to be obligated for administrative costs under this part and part B, including the costs of the direct student loan programs under this part, not to exceed $500,000,000 in each such fiscal year..
---
119-hr-1 | sec. 100004 > (b) Implementation of certain processes

(b)Implementation of certain processes(1)Implementation The Administrator of the Federal Highway Administration shall provide grants to State motor vehicle departments to implement a process to carry out section 180 of title 23, United States Code.(2)Funding Out of any money in the Treasury not otherwise appropriated, $104,000,000 is to remain available until September 30, 2029, beginning in the first fiscal year following the date of enactment of this Act, for grants under paragraph(1).(3)Eligible amounts Each State motor vehicle department may receive not more than $2,000,000 under this subsection.
---

## Label distribution by bill

In [4]:
df.pivot_table(
    index="bill",
    columns="label",
    values="path",
    aggfunc="count",
    fill_value=0,
)

label,appropriation,cap,directive,fee,restriction,transfer,unknown
bill,,,,,,,
118-hr-4366,51,2,4,0,5,4,1
119-hr-1,65,3,0,7,0,0,131

## Coverage check

Verify that `build_financial_df` captures every dollar-amount node — no silent drops.

In [5]:
BILLS_DIR = Path("../bills")
for bill_dir in sorted(BILLS_DIR.iterdir()):
    if not bill_dir.is_dir():
        continue
    xmls = sorted(bill_dir.glob("*.xml"))
    if not xmls:
        continue
    try:
        tree = normalize_bill(xmls[0])
    except Exception as e:
        print(f"SKIP {bill_dir.name}: {e}")
        continue
    df_fin = build_financial_df(tree)
    print(f"{bill_dir.name}:", end=" ")
    check_coverage(df_fin, tree)

118-hr-4366: ✓  All 67 dollar-amount nodes represented (103 rows)
119-hr-1: ✓  All 199 dollar-amount nodes represented (221 rows)

## Unknowns

These are the nodes that need new patterns in `classify_bill.py`.

In [6]:
unknowns = df[df["label"] == "unknown"][["bill", "path", "preview", "body_text"]].reset_index(drop=True)
print(f"{len(unknowns)} unknown nodes")
unknowns[["bill", "path", "preview"]]

132 unknown nodes

,bill,path,preview
0,118-hr-4366,GENERAL PROVISIONS > sec. 418,$0.
1,119-hr-1,sec. 10101 > (a) Reference price,(a)Reference price Section 1111(19) of the Agr...
2,119-hr-1,sec. 10101 > (g) Payment limitations,(g)Payment limitations Section 1001 of the Foo...
3,119-hr-1,sec. 10101 > (i) Marketing loans,(i)Marketing loans(1)Availability of nonrecour...
4,119-hr-1,sec. 10101 > (o) Implementation,(o)Implementation Section 1614(c) of the Agric...
...,...,...,...
127,119-hr-1,sec. 112206 > (a) Earned income tax credit cer...,(a)Earned income tax credit certification prog...
128,119-hr-1,sec. 112206 > (b) Task force to design a priva...,(b)Task force to design a private data bouncin...
129,119-hr-1,sec. 112207 > (b) Appropriation for task force...,(b)Appropriation for task force to design a be...
130,119-hr-1,sec. 112210 > (a) In general,"(a)In general Paragraphs(1),(2),(3),(4), and(5..."
131,119-hr-1,Increase in Debt Limit > sec. 113001,The limitation under section 3101(b) of title ...

### Group by opening text

Frequent openers are the highest-priority patterns to add.

In [7]:
# Group unknown nodes by opening text to find repeated patterns worth adding rules for
unknowns["opener"] = unknowns["body_text"].str[:80]
unknowns["opener"].value_counts().head(30)

opener
(c)Subsequent adjustment Beginning in fiscal year 2026 and each fiscal year ther    7
(b)Fee specified(1)Initial amount The amount specified in this subsection for fi    7
(b)Initial amount For purposes of this subsection, the amount specified in this     4
$0.                                                                                 1
(a)Reference price Section 1111(19) of the Agricultural Act of 2014 (7 U.S.C. 90    1
(g)Payment limitations Section 1001 of the Food Security Act of 1985 (7 U.S.C. 1    1
(i)Marketing loans(1)Availability of nonrecourse marketing assistance loans for     1
(o)Implementation Section 1614(c) of the Agricultural Act of 2014 (7 U.S.C. 9097    1
(p)Livestock safety net updates(1)In general Section 1501(b) of the Agricultural    1
(v)Program compliance and integrity Section 515(l)(2) of the Federal Crop Insura    1
(w)Reviews, compliance, and integrity Section 516(b)(2)(C)(i) of the Federal Cro    1
(a)Grassroots source water protection program Section 1240O(b) of the Food Secur    1
(b)Voluntary public access and habitat incentive program Section 1240R(f)(1) of     1
(c)Feral swine eradication and control pilot program Section 2408(g)(1) of the A    1
(d)Funding(1)In general Section 1241(a) of the Food Security Act of 1985 (16 U.S    1
(b)Foundation for food and agriculture research Section 7601(g)(1)(A) of the Agr    1
(c)Scholarships for students at 1890 Institutions Section 1446 of the National A    1
(d)Assistive technology program for farmers with disabilities Section 1680(c) of    1
(e)Specialty crop research initiative Section 412(k)(1)(B) of the Agricultural R    1
(f)Research Facilities Act Section 6 of the Research Facilities Act (7 U.S.C. 39    1
(d)Rescissions(1)Competitive grants for non-Federal forest landowners All of the    1
(a)Plant pest and disease management and disaster prevention Section 420(f) of t    1
(b)Specialty crop block grants Section 101(l)(1) of the Specialty Crops Competit    1
(c)Organic production and market data initiative Section 7407(d)(1) of the Farm     1
(d)Modernization and improvement of international trade technology systems and d    1
(f)Multiple crop and pesticide use survey Section 10109(c)(1) of the Agriculture    1
(a)Animal Disease Prevention and Management Section 10409A(d)(1) of the Animal H    1
(b)Sheep production and marketing grant program Section 209(c) of the Agricultur    1
(c)Loan limits for unsubsidized loans and certain Federal Direct PLUS Loans(1)An    1
(b)Repayment plans Section 455(d) of the Higher Education Act of 1965 (20 U.S.C.    1
Name: count, dtype: int64

### Inspect full text of a specific unknown

In [8]:
# Read full text of a specific unknown row for pattern investigation
# Change idx to the row number you want to inspect
for _, row in unknowns.iloc[::5].iterrows():
    print(row["bill"], "|", row["path"])
    print()
    print(row["body_text"])
    print("---")

118-hr-4366 | GENERAL PROVISIONS > sec. 418

$0.
---
119-hr-1 | sec. 10101 > (p) Livestock safety net updates

(p)Livestock safety net updates(1)In general Section 1501(b) of the Agricultural Act of 2014 (7 U.S.C. 9081(b)) is amended—(A)by amending paragraph(2) to read as follows:(2)Payment rates(A)Losses due to predation Indemnity payments to an eligible producer on a farm under paragraph(1)(A) shall be made at a rate of 100 percent of the market value of the affected livestock on the applicable date, as determined by the Secretary.(B)Losses due to adverse weather or disease Indemnity payments to an eligible producer on a farm under subparagraph(B) or(C) of paragraph(1) shall be made at a rate of 75 percent of the market value of the affected livestock on the applicable date, as determined by the Secretary.(C)Determination of market value In determining the market value described in subparagraphs(A) and(B), the Secretary may consider the ability of eligible producers to document regional price premiums for affected livestock that exceed the national average market price for those livestock.(D)Applicable date defined In this paragraph, the term applicable date means, with respect to livestock, as applicable—(i)the day before the date of death of the livestock; or(ii)the day before the date of the event that caused the harm to the livestock that resulted in a reduced sale price.; and(B)by adding at the end the following:(5)Additional payment for unborn livestock(A)In general In the case of unborn livestock death losses incurred on or after January 1, 2024, the Secretary shall make an additional payment to eligible producers on farms that have incurred such losses in excess of the normal mortality due to a condition specified in paragraph(1).(B)Payment rate Additional payments under subparagraph(A) shall be made at a rate—(i)determined by the Secretary; and(ii)less than or equal to 85 percent of the payment rate established with respect to the lowest weight class of the livestock, as determined by the Secretary, acting through the Administrator of the Farm Service Agency.(C)Payment amount The amount of a payment to an eligible producer that has incurred unborn livestock death losses shall be equal to the payment rate determined under subparagraph(B) multiplied, in the case of livestock described in—(i)subparagraph(A),(B), or(F) of subsection(a)(4), by 1;(ii)subparagraph(D) of such subsection, by 2;(iii)subparagraph(E) of such subsection, by 12; and(iv)subparagraph(G) of such subsection, by the average number of birthed animals (for one gestation cycle) for the species of each such livestock, as determined by the Secretary.(D)Unborn livestock death losses defined In this paragraph, the term unborn livestock death losses means losses of any livestock described in subparagraph(A),(B),(D),(E),(F), or(G) of subsection(a)(4) that was gestating on the date of the death of the livestock..(2)Livestock forage disaster program Section 1501(c)(3)(D)(ii)(I) of the Agricultural Act of 2014 (7 U.S.C. 9081(c)(3)(D)(ii)(I)) is amended—(A)by striking 1 monthly payment and inserting 2 monthly payments; and(B)by striking county for at least 8 consecutive and inserting the following: county for not less than—(aa)4 consecutive weeks during the normal grazing period for the county, as determined by the Secretary, shall be eligible to receive assistance under this paragraph in an amount equal to 1 monthly payment using the monthly payment rate determined under subparagraph(B); or(bb)any of the 7 of the previous 8 consecutive.(3)Emergency assistance for livestock, honey bees, and farm-raised fish Section 1501(d) of the Agricultural Act of 2014 (7 U.S.C. 9081(d)) is amended by adding at the end the following:(5)Assistance for losses due to bird depredation(A)Payments Eligible producers on a farm of farm-raised fish, including fish grown as food for human consumption, shall be eligible to receive payments under this subsection to aid in the reduction of losses due to piscivorous birds.(B)Payment rate(i)In general The payment rate for payments under subparagraph(B) shall be determined by the Secretary, taking into account—(I)costs associated with the deterrence of piscivorous birds; (II)the value of lost fish and revenue due to bird depredation; and (III)costs associated with disease loss from bird depredation.(ii)Minimum rate The payment rate for payments under subparagraph(B) shall be not less than $600 per acre of farm-raised fish.(C)Payment amount The amount of a payment under subparagraph(B) shall be the product obtained by multiplying—(i)the applicable payment rate under subparagraph(C); and(ii)85 percent of the total number of acres of farm-raised fish farms that the eligible producer has in production for the calendar year..(4)Tree assistance program Section 1501(e) of the Agricultural Act of 2014 (7 U.S.C. 9081(e)) is amended—(A)in paragraph(2)(B), by striking 15 percent (adjusted for normal mortality) and inserting normal mortality; and(B)in paragraph(3)—(i)in subparagraph(A)(i), by striking 15 percent mortality (adjusted for normal mortality) and inserting normal mortality; and(ii)in subparagraph(B)—(I)by striking 50 and inserting 65; and (II)by striking 15 percent damage or mortality (adjusted for normal tree damage and mortality) and inserting normal tree damage or mortality.
---
119-hr-1 | sec. 10102 > (c) Feral swine eradication and control pilot program

(c)Feral swine eradication and control pilot program Section 2408(g)(1) of the Agriculture Improvement Act of 2018 (7 U.S.C. 8351 note; Public Law 115–334) is amended—(1)by striking and and inserting a comma; and(2)by inserting , and $15,000,000 for each of fiscal years 2025 through 2031 before the period at the end.
---
119-hr-1 | sec. 10104 > (e) Specialty crop research initiative

(e)Specialty crop research initiative Section 412(k)(1)(B) of the Agricultural Research, Extension, and Education Reform Act of 1998 (7 U.S.C. 7632(k)(1)(B)) is amended by striking section $80,000,000 for fiscal year 2014 and inserting the following: section—(i)$80,000,000 for each of fiscal years 2014 through 2025; and(ii)$175,000,000 for fiscal year 2026.
---
119-hr-1 | sec. 10107 > (c) Organic production and market data initiative

(c)Organic production and market data initiative Section 7407(d)(1) of the Farm Security and Rural Investment Act of 2002 (7 U.S.C. 5925c(d)(1)) is amended—(1)in subparagraph(B), by striking and at the end;(2)in subparagraph(C), by striking the period at the end and inserting ; and; and(3)by adding at the end the following:(D)$10,000,000 for the period of fiscal years 2026 through 2031..
---
119-hr-1 | sec. 30011 > (c) Loan limits for unsubsidized loans and certain Federal Direct PLUS Loans

(c)Loan limits for unsubsidized loans and certain Federal Direct PLUS Loans(1)Annual and aggregate unsubsidized loan limits Section 455(a) of the Higher Education Act of 1965 (20 U.S.C. 1087e(a)) is further amended by adding at the end the following:(5)Annual and aggregate unsubsidized loan limits(A)Undergraduate students(i)Annual loan limits Notwithstanding any provision of this part or part B, subject to subparagraph(C) and except as provided in paragraph(4), beginning on July 1, 2026, the maximum annual amount of Federal Direct Unsubsidized Stafford loans that an undergraduate student may borrow in any academic year (as defined in section 481(a)(2)) or its equivalent shall be the difference between—(I)the amount of the median cost of college of the program of study in which the student is enrolled; and (II)the amount of the Federal Pell Grant under section 401 awarded to the student for such academic year.(ii)Aggregate limits Notwithstanding any provision of this part or part B, except as provided in paragraph(4), beginning on July 1, 2026, the maximum aggregate amount of Federal Direct Unsubsidized Stafford loans that a student may borrow for programs of study that award an undergraduate credential upon completion of such a program shall be $50,000.(B)Graduate and professional students(i)Annual limits Notwithstanding any provision of this part or part B, subject to subparagraph(C) and except as provided in paragraph(4), beginning on July 1, 2026, the maximum annual amount of Federal Direct Unsubsidized Stafford loans that a graduate student or professional student may borrow in any academic year (as defined in section 481(a)(2)) or its equivalent shall be the amount of the median cost of college of the program of study in which the student is enrolled.(ii)Aggregate limits Notwithstanding any provision of this part or part B, except as provided in paragraph(4), beginning on July 1, 2026, the maximum aggregate amount of Federal Direct Unsubsidized Stafford loans that, in addition to the maximum aggregate amount described in subparagraph(A)(ii)—(I)a graduate student—(aa)who is not (and has not been) a professional student, may borrow for programs of study described in subparagraph(D)(i) shall be $100,000; or(bb)who is (or has been) a professional student, may borrow for programs of study described in subparagraph(D)(i) shall be an amount equal to— (AA)$150,000, minus (BB)the amount such student borrowed for programs of study described in subclauses(I) and (II) of subparagraph(D)(ii); and (II)a professional student—(aa)who is not (and has not been) a graduate student, may borrow for programs of study described in subclauses(I) and (II) of subparagraph(D)(ii) shall be $150,000; or(bb)who is (or has been) a graduate student, may borrow for programs of study described in subclauses(I) and (II) of subparagraph(D)(ii) shall be an amount equal to— (AA)$150,000, minus (BB)the amount such student borrowed for programs of study described in subparagraph(D)(i).(C)Less than full-time enrollment In any case where a student is enrolled in an program of study of an institution of higher education on less than a full-time basis during any academic year, the amount of a loan that student may borrow for an academic year (as defined in section 481(a)(2)) or its equivalent shall be reduced in direct proportion to the degree to which that student is not so enrolled on a full-time basis, rounded to the nearest whole percentage point, as provided in a schedule of reductions published by the Secretary computed for purposes of this paragraph.(D)Definition For purposes of this subsection:(i)Graduate student The term graduate student means a student enrolled in a program of study that awards a graduate credential (other than a professional degree) upon completion of the program.(ii)Professional student The term professional student means a student enrolled in a program of study that—(I)awards a professional degree upon completion of the program; or (II)provides the training described in part 141 of title 14, Code of Federal Regulations (or any successor regulations).(iii)Undergraduate student The term undergraduate student means a student enrolled in a program of study that awards an undergraduate credential upon completion of the program..(2)Annual and aggregate Federal direct PLUS loans limits for parent borrowers Section 455(a) of the Higher Education Act of 1965 (20 U.S.C. 1087e(a)) is further amended by adding at the end the following:(6)Annual and aggregate Federal direct PLUS loans limits for parent borrowers(A)Annual limits Notwithstanding any provision of this part or part B, subject to paragraph(3)(E) and except as provided in paragraph(4), beginning on July 1, 2026, the maximum annual amount of Federal Direct PLUS loans that a parent may borrow, on behalf of a dependent student, in any academic year (as defined in section 481(a)(2)) or its equivalent shall be the amount equal to—(i)the cost of attendance of the program of study of such student; minus(ii)the maximum annual amount of Federal Direct Unsubsidized Stafford loans such student may borrow in such academic year.(B)Aggregate limits Notwithstanding any provision of this part or part B, subject to paragraph(3)(E) and except as provided in paragraph(4), beginning on July 1, 2026, the maximum aggregate amount of Federal Direct PLUS loans that a parent may borrow shall be $50,000, without regard to the number of dependent students on behalf of whom such parent borrows such a loan..(3)Lifetime maximum aggregate amount for all students Section 455(a) of the Higher Education Act of 1965 (20 U.S.C. 1087e(a)) is further amended by adding at the end the following:(7)Lifetime maximum aggregate amount for all students Notwithstanding any provision of this part or part B, except as provided in paragraph(4), beginning on July 1, 2026, the maximum aggregate amount of loans made, insured, or guaranteed under this title that a student may borrow, and that a parent may borrow on behalf of such student, shall be $200,000, without regard to any amounts repaid, forgiven, canceled, or otherwise discharged on any such loan..(4)Institutionally determined limits Section 455(a) of the Higher Education Act of 1965 (20 U.S.C. 1087e(a)) is further amended by adding at the end the following:(8)Institutionally determined limits Notwithstanding the annual loan limits described in subparagraphs(A)(i) and(B)(i) of paragraph(5) and subparagraph(A) of paragraph(6), beginning on July 1, 2026, an institution of higher education (at the discretion of a financial aid administrator at the institution) may limit the total amount of loans made under this part for a program of study for an academic year (as defined in section 481(a)(2)) that a student may borrow, and that a parent may borrow on behalf of such student, as long as any such limit is applied consistently to all students enrolled in such program of study..
---
119-hr-1 | Energy > sec. 41003

Section 3 of the Natural Gas Act (15 U.S.C. 717b) is amended by adding at the end the following:(g)Charge for exportation or importation of natural gas The Secretary of Energy shall, by rule, impose and collect, for each application to export natural gas from the United States to a foreign country with which there is not in effect a free trade agreement requiring national treatment for trade in natural gas, or to import natural gas from such a foreign country, a nonrefundable charge of $1,000,000, and, for purposes of subsection(a), the importation or exportation of natural gas that is proposed in an application for which such a nonrefundable charge was imposed and collected shall be deemed to be in the public interest, and such an application shall be granted without modification or delay..
---
119-hr-1 | sec. 44109 > (a) Revising home equity limit

(a)Revising home equity limit Section 1917(f)(1) of the Social Security Act (42 U.S.C. 1396p(f)(1)) is amended—(1)in subparagraph(B)—(A)by striking A State and inserting(i) A State;(B)in clause(i), as inserted by subparagraph(A)—(i)by striking $500,000 and inserting the amount specified in subparagraph(A); and(ii)by inserting , in the case of an individual’s home that is located on a lot that is zoned for agricultural use, after apply subparagraph(A); and(C)by adding at the end the following new clause:(ii)A State may elect, without regard to the requirements of section 1902(a)(1) (relating to statewideness) and section 1902(a)(10)(B) (relating to comparability), to apply subparagraph(A), in the case of an individual’s home that is not described in clause(i), by substituting for the amount specified in such subparagraph, an amount that exceeds such amount, but does not exceed $1,000,000. ; and(2)in subparagraph(C)—(A)by inserting (other than the amount specified in subparagraph(B)(ii) (relating to certain non-agricultural homes)) after specified in this paragraph; and(B)by adding at the end the following new sentence: In the case that application of the preceding sentence would result in a dollar amount (other than the amount specified in subparagraph(B)(i) (relating to certain agricultural homes)) exceeding $1,000,000, such amount shall be deemed to be equal to $1,000,000..
---
119-hr-1 | sec. 70002 > (c) Subsequent adjustment

(c)Subsequent adjustment Beginning in fiscal year 2026 and each fiscal year thereafter, the amount specified in this section for a fiscal year shall be equal to the sum of—(1)the amount imposed under this section for the prior fiscal year; and(2)rounded to the next lowest multiple of $10, the amount referred to in paragraph(1), multiplied by the percentage (if any) by which the Consumer Price Index for All Urban Consumers for the month of July preceding the date on which such adjustment takes effect exceeds the Consumer Price Index for All Urban Consumers for the same month of the preceding calendar year.
---
119-hr-1 | sec. 70005 > (b) Initial amount

(b)Initial amount For purposes of this subsection, the amount specified in this section for fiscal year 2025 shall be such amount as the Secretary may by rule provide, but in any event not less than $500.
---
119-hr-1 | sec. 70007 > (c) Subsequent adjustment

(c)Subsequent adjustment Beginning in fiscal year 2026 and each fiscal year thereafter, the amount specified in this section for a fiscal year shall be equal to the sum of—(1)the amount imposed under this section for the prior fiscal year; and(2)rounded to the next lowest multiple of $10, the amount referred to in paragraph(1), multiplied by the percentage (if any) by which the Consumer Price Index for All Urban Consumers for the month of July preceding the date on which such adjustment takes effect exceeds the Consumer Price Index for All Urban Consumers for the same month of the preceding calendar year.
---
119-hr-1 | sec. 70014 > (b) Fee specified

(b)Fee specified(1)Initial amount The amount specified in this subsection for fiscal year 2025 shall be such amount as the Secretary may by rule provide, but in any event not less than $550.(2)Subsequent adjustment Beginning in fiscal year 2026 and each fiscal year thereafter, the amount specified in this subsection for a fiscal year shall be equal to the sum of—(A)the amount imposed under this subsection for the prior fiscal year; and(B)rounded to the next lowest multiple of $10, the amount referred to in subparagraph(A), multiplied by the percentage (if any) by which the Consumer Price Index for All Urban Consumers for the month of July preceding the date on which such adjustment takes effect exceeds the Consumer Price Index for All Urban Consumers for the same month of the preceding calendar year.
---
119-hr-1 | sec. 70016 > (c) Fee for filing an application for temporary protected status


## False positive check

Spot-check `PRIMARY_LABELS` nodes — especially useful once non-appropriations bills are in the mix.

In [9]:
# Spot-check PRIMARY_LABELS nodes in non-appropriations bills
# Look for nodes labelled appropriation/transfer/rescission that shouldn't be
primary = df[df["label"].isin(PRIMARY_LABELS)]
for _, row in primary.sample(min(15, len(primary)), random_state=42).iterrows():
    print(f"[{row['bill']}] [{row['label']}]")
    print(row["body_text"][:200])
    print()

[118-hr-4366] [appropriation]
For military and naval insurance, national service life insurance, servicemen's indemnities, service-disabled veterans insurance, and veterans mortgage life insurance as authorized by chapters 19 and

[119-hr-1] [appropriation]
(a)Appropriation In addition to amounts otherwise available, there is appropriated to the Office of Refugee Resettlement for fiscal year 2025, out of any money in the Treasury not otherwise appropriat

[119-hr-1] [appropriation]
(d)CBP vehicles In addition to amounts otherwise available, there is appropriated to the Commissioner of U.S. Customs and Border Protection for fiscal year 2025, out of any money in the Treasury not o

[119-hr-1] [appropriation]
(a)Appropriations In addition to amounts otherwise available, there are appropriated to the Secretary of Defense for fiscal year 2025, out of any money in the Treasury not otherwise appropriated, to r

[118-hr-4366] [appropriation]
For grants to assist States to acquire or construct State nursing home and domiciliary facilities and to remodel, modify, or alter existing hospital, nursing home, and domiciliary facilities in State

[119-hr-1] [appropriation]
(a)Appropriation In addition to amounts otherwise available, there is appropriated to U.S. Immigration and Customs Enforcement for fiscal year 2025, out of any money in the Treasury not otherwise appr

[119-hr-1] [appropriation]
(c)CBP retention and hiring bonuses In addition to amounts otherwise available, there is appropriated to the Commissioner of U.S. Customs and Border Protection for fiscal year 2025, out of any money i

[119-hr-1] [appropriation]
(a)Public confirmation of authorized motor carriers There is appropriated $5,000,000 to the Administrator of the Federal Motor Carrier Safety Administration to establish a public website to present da

[119-hr-1] [appropriation]
(a)Appropriation In addition to amounts otherwise available, there is appropriated to the Department of Justice for fiscal year 2025, out of any money in the Treasury not otherwise appropriated, $500,

[119-hr-1] [appropriation]
(a)DOD appropriations In addition to amounts otherwise available, there are appropriated to the Secretary of Defense for fiscal year 2025, out of any money in the Treasury not otherwise appropriated,

[118-hr-4366] [appropriation]
For grants to assist States and tribal organizations in establishing, expanding, or improving veterans cemeteries as authorized by section 2408 of title 38, United States Code, $60,000,000, to remain

[118-hr-4366] [appropriation]
For construction, acquisition, expansion, rehabilitation, and conversion of facilities for the training and administration of the Army National Guard, and contributions therefor, as authorized by chap

[118-hr-4366] [appropriation]
For the Department of Defense Family Housing Improvement Fund, $6,611,000, to remain available until expended, for family housing initiatives undertaken pursuant to section 2883 of title 10, United St

[119-hr-1] [appropriation]
(a)Appropriation In addition to amounts otherwise available, there is appropriated to U.S. Immigration and Customs Enforcement for fiscal year 2025, out of any money in the Treasury not otherwise appr

[118-hr-4366] [appropriation]
For necessary expenses of the National Cemetery Administration for operations and maintenance, not otherwise provided for, including uniforms or allowances therefor; cemeterial expenses as authorized